import React, { forwardRef } from "react";

const classTypes = {
  radio:
    "relative float-left -ml-6 mr-1 mt-0.5 h-5 w-5 appearance-none rounded-full border-2 border-solid border-text-brand before:pointer-events-none before:absolute before:h-4 before:w-4 before:scale-0 before:rounded-full before:bg-transparent before:opacity-0 before:shadow-[0px_0px_0px_13px_transparent] before:content-'' after:absolute after:z-1 after:block after:h-4 after:w-4 after:rounded-full after:content-'' checked:border-brandText checked:before:opacity-0.16 checked:after:absolute checked:after:left-1/2 checked:after:top-1/2 checked:after:h-2.5 checked:after:w-2.5 checked:after:rounded-full checked:after:border-brandText checked:after:bg-brandText checked:after:content-'' checked:after:[transform:translate(-50%,-50%)] hover:cursor-pointer hover:before:opacity-0.04 hover:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:shadow-none focus:outline-none focus:ring-0 focus:before:scale-100 focus:before:opacity-0.12 focus:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:before:transition-[box-shadow_0.2s,transform_0.2s] checked:focus:border-brandText",
  checkbox:
    "relative float-left -ml-6 mr-1 mt-0.5 h-5 w-5 appearance-none rounded-[0.25rem] border-[0.125rem] border-solid border-brandText outline-none before:pointer-events-none before:absolute before:h-[0.875rem] before:w-[0.875rem] before:scale-0 before:rounded-full before:bg-transparent before:opacity-0 before:shadow-[0px_0px_0px_13px_transparent] before:content-[''] checked:border-brandText checked:bg-brandText checked:before:opacity-[0.16] checked:after:absolute checked:after:-mt-px checked:after:ml-[0.25rem] checked:after:block checked:after:h-[0.8125rem] checked:after:w-[0.375rem] checked:after:rotate-45 checked:after:border-[0.125rem] checked:after:border-l-0 checked:after:border-t-0 checked:after:border-solid checked:after:border-background checked:after:bg-transparent checked:after:content-[''] hover:cursor-pointer hover:before:opacity-[0.04] hover:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:shadow-none focus:transition-[border-color_0.2s] focus:before:scale-100 focus:before:opacity-[0.12] focus:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:before:transition-[box-shadow_0.2s,transform_0.2s] focus:after:absolute focus:after:z-[1] focus:after:block focus:after:h-[0.875rem] focus:after:w-[0.875rem] focus:after:rounded-[0.125rem] focus:after:content-[''] checked:focus:before:scale-100 checked:focus:before:shadow-[0px_0px_0px_13px_#3b71ca] checked:focus:before:transition-[box-shadow_0.2s,transform_0.2s] checked:focus:after:-mt-px checked:focus:after:ml-[0.25rem] checked:focus:after:h-[0.8125rem] checked:focus:after:w-[0.375rem] checked:focus:after:rotate-45 checked:focus:after:rounded-none checked:focus:after:border-[0.125rem] checked:focus:after:border-l-0 checked:focus:after:border-t-0 checked:focus:after:border-solid checked:focus:after:border-background checked:focus:after:bg-transparent",
  text: "flex w-full px-4 py-3 border-none autofill:bg-interactive-interactive01 ring-offset-background text-brand focus-visible:outline-none focus-visible:bg-interactive-interactive01 rounded focus-visible:ring-0 ring-0 focus-visible:ring-offset-0 placeholder:text-t-placeholder input-text-field h-10 p-0 bg-transparent border-transparent",
};

const Input = forwardRef(({ type = "text", ...rest }, ref) => {
  const classType = classTypes[type] || classTypes.text;
  return <input ref={ref} type={type} {...rest} className={classType} />;
});
Input.displayName = "Input"; // Add this line

export default Input;
